language: python
python:
- '3.6'
install:
- pip install ansible molecule apache-libcloud testinfra
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: RP9Eohgs47deIqe5YhwN85PJmXEMu3Df/ZNM2rwVOV0nlQeM30fxj8okD5udh08kqD6QTte6khECSCR0woOlZ+dvHAbyiaQPAA6CasJfCpCX9Y/Zyq70WcuMgjIwWi2NXB29Xjv/QlxaGl/pglT46pHT8fdig9naVV6HRQfhCjtzatCZNRDvUPRMVyucQwHsaNQLZSaSsCRvmTL8vMT32JYtHEKUUTtEVZkFQeGr5f/0flKwFJSamBa4I2ROjlFOOHwF7f1YNm8QKj1qshmOPpouffv97W1HIn2FK3zoxEchndhjEapZtwehlQivm5qn9dH5vQ1ALuasEYTPpKsXmNSMtYknTKo14cq3clt6qFWEVRBXO1dalat0K4ILjg/Va0a7Cqe+HDolVpoFkbKKtYrRSYRVR6qio2bwASNIzYAOFII/GoSy6fAiC6SCINatz3n0mumx3BAPQgtfTDjIvYRiOgYwaKPov875AwvAw//Zwe14oed3HG4lCTN63GAgxsyYxUVmFNI8VZzGD+BFEkL2aBB2Sc4//54qG9lnEENYMVW/kwBUZg7Qjr/Ru3N7ZIjJaAaDCS6JkKc4Xm1V7H10MJ/Mew3HPIoQq2AU/Hhyx8ULaREra38c37v4+9A16UIQBoWOwikJ9ywHSw+eWEoTVSS69yAQOmvok84RFeI=
  - secure: DPAQlvWMDuT+NcLAcR7ht5ozPPWvpcqFKIQ47pjVqLviavRFTiZtJFSaNaVl9UZltgotJBE7cGwX+3w8lfTsPc2665/wDVTUIIpntk462s+Gn8BoqxeF56Er37PWqjCueqmekDmyyEUDb5RhgezqJuF0OCaIVpqgob3CQCaNiCEjp0FV+bh+oN1IvWlxshH1awYSTQ395Z6KLIWyVld3YOVW3S78Au1WbsPlJqb736/569hIcmEeQIvhIU+F/URNP5thLHcsx+k6amRBubf+RMCGBX730lageLKNeMhrI/NddokNPQBLjcTUdD3779WGh5LAbCG8RQU0V2f/9XR2d157+pOXXmFhLsx5EdnDidyFDJUvu42VmgykliXXvHSJPXTgJsc5JBAv9oKgSQaUnFAVr/y5qB9sKmKxnQM0cmyNdbqEWVG/HyhemvCgz+2/vk3x6rd+JpQaW8ZS/NJxNmQ6rnd6p3cbmlRtDSWYOTFQWT5mTHqKqEJjS8UCjS5AKwS5uEokVLb5AncHi++YQc5n55QEQPkhTL3kgy/8ZFLSv7PcYleDk3dOYfL5pQYlip+LRtvuKptjEAC55xXItXaeY7JTRY6TIoyxrXRWYiZ0ttRurfG+3Dvxee5NfIGkl9pD4e9nk/8JrrZTz41gmYA0b1/Ldrt0NHEVcQmbVxU=
  - secure: Bm4JwUXO5R2NJFt1I1SETb/ilfEWN8d1eiQffq0emuPMPG5ICittRkYiIvWP3aU5z2jxXGePyScdy0VfYsxI16/KSCoF7ziiYZpofX5SWu7ePG/Q6VonUc97csQQDa1C0wLb5B0EN8p9xQwtWa6CPAocPEjn8YJVYAnWAiDJCF95oUBk4vjBY98OEXthjrChTyQrzRvylDn36hdLcq+V7IUNn+qtMwosd62buoL/jFwPIe5rl/Qxc9qSi3sg6T0HjSvHxFjhH69XNjrPacfKphRGK0K30TpvIqWlE8NFCFN7Ckw5Po9AQepP/bhDnP5ahBSt6cbhp6RHNFKO/CVsoamVgrRlW3xSwC8d+KYU+tDmsM50eKenfH9nlYifCaCM6QkEnQ46bQO5B00z88oiilmfy6vjruifWC8wlxMiJKWxWJY9g9aBWNTg0VkhcrGQHfhA3GRxaqTlXTsklonBMNw4BvrE4NQkHpIfZKQ6gF5kRX7SwiQ1owTzkdO1B7c0jyOlK389jV9C0uNiyglDAl/3VjAh0e/i9YS8Du7DgjKv5dgpJSbZ6oTSaJn2m4oPW2iWWLnmwrJJqD6qi9Ngw72NkIdvkRwzf1QOsX+ZckxSyvmsLp4FrNiDQhdtRyY5eI+ODXsmMX5reuHhv2IgmpsrOPpNePYRD8XoiO3i9Pc=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_a81607098ed7_key -iv $encrypted_a81607098ed7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: XwQoY/Dvbm0Fo0aBwhBsRK4jeZc8fL1mceK+5qVfe4+kkTSCeLjSu22btHYRNlplPVjSYTbKIXONYowP2qWKfOZQwRxnA+mG3DWfkSiEBQt23mhksnfxnr1ysys8J7q0eMq//ssMEVot8kCuyISVo9tlb1IEpnCTGevsG80MH/rpSKii0wJC9t4mg0EPlFPpqGcqEw48gGAvCRhkc7RQ/FvngGzM3cSof9MK7bm6RyIwpKIlL8ZmUnis00Tp1fKETzT2dEHb6OOAYwhSavhbjQDHxvzRhOuO6k29YmOW8HZoYL909HpDsL6RwrD6VWB550logcgbW0PS+mUTvvorN/ZSRwroKSYskOsSsoiPPb9xrFVGJhuP4Sv0Ne+2bnQA6PmI7Qy4grpNSMdeyP8/DWyH87vPk2J4f8ppI4BdkwjRk+W7Q5HJGpf6HTnIzraTvVKoQp7bTovYi0OMVQhrV9QvyN7Ub01QRLF0asiTYMJf2k3qNVgde/fU5qu/1x2s+ujb2lnew5hqlXJqoTNx/WjdBvVphNQ1Fr2sBXssRmM77cZlDzZk1vVicySximx+3IpSsXpqnTAE+de/V6xp41hJuVAgztI0ujcbwCpckcuzuVBxHtjO88qaWBl325jCjuJBmOMZ5999Djd53gENwV8vOf3OcsAhBxryBmaGHSo=
